describe("Smoke tests", () => {
  // it('Register a new user', () => {
  //   cy.get('ul').find('li').contains('a', 'Create an account').click()
  //   cy.get('#firstname').click().type('John')
  //   cy.get('#lastname').click().type('Doe')
  //   cy.get('#email_address').click().type('johnny.doe@gmail.com')
  //   cy.get('#password').click().type('Password1')
  //   cy.get('#password-confirmation').click().type('Password1')
  //   cy.get('#form-validate').find('button[type="submit"]').click()
  //   cy.url().should('include', '/customer/account/index')
  // })
    it("Login with valid credentials", () => {
     cy.login('johnny.doe@gmail.com', 'Password1')
    })
    it("Get a list of shirts from search", () => {
      cy.visit("/")
      cy.get("#search").click().type("shirt{enter}")
      cy.url().should("include", "shirt")
      cy.get("ol.product-items").should("have.length.above", 0)
    })

    it("Add item to cart", () => {
      cy.openItemPage();
      cy.get(".swatch-option.text").first().click()
      cy.get(".swatch-option.color").first().click()
      cy.get("#product-addtocart-button").click()
      cy.get('[data-ui-id="message-success"]')
      cy.get(".showcart").click()
      cy.get('[data-ui-id="page-title-wrapper"]')
        .invoke("text")
        .then((title) => {
          cy.get(".viewcart").click()
          cy.get(".product-item-name").contains(title).should("be.visible")
        })
    })

    it("Place an order", () => {
      cy.openItemPage();
      cy.get(".swatch-option.text").first().click()
      cy.get(".swatch-option.color").first().click()
      cy.get("#product-addtocart-button").click()
      cy.get('[data-ui-id="message-success"]')
      cy.get(".showcart").click()
      cy.get(".viewcart").click()
      cy.get('#cart-totals', { timeout: 10000 }).contains('Order Total')
      cy.get('[data-role="proceed-to-checkout"]').click()
      cy.url().should('include', 'checkout')
      cy.get('#shipping').should('be.visible')
      cy.get('#customer-email').type('johnny.doe@gmail.com')
      cy.get('[name="firstname"]').type('John')
      cy.get('[name="lastname"]').type('Doe')
      cy.get('[name="street[0]"]').type('Address')
      cy.get('[name="city"]').type('Osijek')
      cy.get('[name="country_id"]').select('Croatia')
      cy.get('[name="region_id"]').select('Osječko-baranjska županija')
      cy.get('[name="postcode"]').type('31000')
      cy.get('[name="telephone"]').type('091911911')
      cy.get('[name="ko_unique_1"]').check()
      cy.get('[data-role="opc-continue"]').click()
      cy.url().should('include', 'payment')
      cy.get('#billing-address-same-as-shipping-checkmo').check()
      cy.get('.checkout').click()
      cy.url().should('include', 'success')
    })

    it("Sign out logged in user", () => {
      cy.login('johnny.doe@gmail.com', 'Password1')
      cy.get('[data-action="customer-menu-toggle"]').first().click()
      cy.get('.authorization-link').first().click()
      cy.url().should('include', 'logoutSuccess')
    })

    it("Remove item from cart", () => {
       cy.openItemPage()
      cy.get(".swatch-option.text").first().click()
      cy.get(".swatch-option.color").first().click()
      cy.get("#product-addtocart-button").click()
      cy.get('[data-ui-id="message-success"]') 
      cy.get(".showcart").click()
      cy.get('[data-ui-id="page-title-wrapper"]')
        .invoke("text")
        .then((title) => {
          cy.get(".viewcart").click()
          cy.get(".product-item-name").contains(title)
        })
      cy.get('.action-delete').click()
      cy.get('.cart-empty').should('be.visible')
    })

  it("Users cart items saved after relogin", () => {
    cy.login('johnny.doe@gmail.com', 'Password1')
    cy.openItemPage()
    cy.get(".swatch-option.text").first().click()
    cy.get(".swatch-option.color").first().click()
    cy.get("#product-addtocart-button").click()
    cy.get('[data-ui-id="message-success"]')
    cy.get('[data-ui-id="page-title-wrapper"]')
      .invoke("text")
      .then((title) => {
        cy.get('[data-action="customer-menu-toggle"]').first().click()
        cy.get(".authorization-link").first().click()
        cy.url().should("include", "logoutSuccess")
        cy.url().should("include", "")
        cy.get("ul").find("li").contains("a", "Sign In").click()
        cy.get("#email").click().type("johnny.doe@gmail.com")
        cy.get("#pass").click().type("Password1")
        cy.get("#send2").click()
        cy.contains("Welcome, John Doe!")
        cy.get(".showcart").click()
        cy.get(".viewcart").click()
        cy.get(".product-item-name").contains(title).should("be.visible")
      })
  })
})
